---
- name: Run against all hosts
  hosts: all
  tasks:
    # Check Version
    - name: Get OpenSSH version. Testing to see if this works.
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ssh -V 2>&1 | grep "OpenSSH" | sed -n "s/.*OpenSSH_\([0-9.]*\).*/\1/p"
        executable: /bin/bash
      register: openssh_version
      changed_when: openssh_version.rc != 0

    - name: Display SSH Version
      ansible.builtin.debug:
        var: openssh_version.stdout

    - name: Get Support Key Types
      ansible.builtin.shell:
        cmd: ssh -Q key 2>&1
        executable: /bin/bash
      register: openssh_keytypes
      changed_when: openssh_keytypes.rc != 0

    - name: Distribute ssh-ed25519 keys
      when: "'ssh-ed25519' in openssh_keytypes.stdout_lines"
      block:
        - name: Gather and distribute ed25519 SSH public keys on supported hosts
          ansible.posix.authorized_key:
            user: "{{ ansible_user_id }}"
            key: "{{ lookup('file', item) }}"
            state: present
          with_fileglob:
            - keys/id_ed25519*.pub

    - name: Distribute RSA Keys (Fallback)
      when: "'ssh-ed25519' not in openssh_keytypes.stdout_lines and 'sk-ssh-ed25519@openssh.com' not in openssh_keytypes.stdout_lines"
      block:
        - name: Gather and distribute RSA SSH public keys. This host does not support ed25519 keys.
          ansible.posix.authorized_key:
            user: "{{ ansible_user_id }}"
            key: "{{ lookup('file', item) }}"
            state: present
          with_fileglob:
            - keys/id_rsa*.pub
