name: ansible-lint
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@da68a70d7686164e7e9aa098e850b56c8d858209 # main
